language: java
before_install:
  - chmod +x mvnw
addons:
  sonarcloud:
    organization: "ragilpersonal"
    token:
      secure: "$SONAR_TOKEN"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=RagilPersonal_shop


